name: Application-Pipeline
# trigger:
# - main
stages:
  - stage: Build_Application
    displayName: 'Build Application'
    jobs:
    - job: Build_Application
      pool:
        name: Azure Pipelines
      steps:
      - task: Docker@0
        displayName: 'Build an image'
        inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: 'cloudprojectsp'
          azureContainerRegistry: '$(azurecontainerregistry)'
          action: 'Build an image'
          dockerFile: '**/Dockerfile'
          imageName: '$(Build.Repository.Name):popularapp'

      - task: Docker@0
        displayName: 'Push an image'
        inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: 'cloudprojectsp'
          azureContainerRegistry: '$(azurecontainerregistry)'
          action: 'Push an image'
          imageName: 'cloudprojectacr.azurecr.io/promiseuche/cloud-project:popularapp'

  - stage: Deploy_Application
    displayName: 'Deploy Application'
    jobs:
    - job: Deploy_Application
      pool:
        name: Azure Pipelines
      steps:
      - task: KubectlInstaller@0
        inputs:
          kubectlVersion: 'latest' 
      - task: Kubernetes@1
        displayName: Apply kubernetes file
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscriptionEndpoint: 'cloudprojectsp'
          azureResourceGroup: 'cloudproject'
          kubernetesCluster: 'cloudproject'
          namespace: 'default'
          command: 'apply'
          configurationType: 'configuration'
          configuration: $(System.DefaultWorkingDirectory)/Application/kubernetes-deploy.yml
          arguments: '-f $(System.DefaultWorkingDirectory)/Application/kubernetes-deploy.yml'
      - powershell: |
          az login --service-principal -u $(appid) -p $(pass) --tenant $(tenant)
          az account set --subscription $(subscription)
          az aks get-credentials --resource-group cloudproject --name cloudproject
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          kubectl create ns prometheus
          helm install prometheus prometheus-community/kube-prometheus-stack -n prometheus
          kubectl get all -n prometheus
        name: Deploy_Prometheus_Graphana